name: Ubuntu

on:
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Visit https://remotedesktop.google.com/headless & paste the authorization code'
        required: true
      pincode:
        description: 'Enter a pin code'
        default: '123456'
        required: true
      authtoken:
        description: 'PINGGY_AUTH_TOKEN'
        required: true
      computername:
        description: 'MACHINE_NAME'
        default: 'ubuntu'
        required: true
      username:
        description: 'USER_NAME'
        default: 'devbox'
        required: true
      password:
        description: 'USER_PASSWORD'
        default: 'box123'
        required: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3.0.2
    - name: Mask Code & Pin
      run: |
        _Token=$(jq -r '.inputs.authtoken' $GITHUB_EVENT_PATH)
        _CName=$(jq -r '.inputs.computername' $GITHUB_EVENT_PATH)
        _Pass=$(jq -r '.inputs.password' $GITHUB_EVENT_PATH)
        echo ::add-mask::$_Token
        echo ::add-mask::$_CName
        echo ::add-mask::$_Pass
        echo PINGGY_TOKEN="$_Token" >> $GITHUB_ENV
        echo ComputerName="$_CName" >> $GITHUB_ENV
        echo Password="$_Pass" >> $GITHUB_ENV
    - name: Setup Environment
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y
    - name: Installing Desktop Environment
      run: sudo bash Ubuntu.sh
#    - name: Starting Chrome Remote Desktop
#      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Setting up Pinggy
      run:  bash Setup.sh "${{ env.ComputerName }}" "${{ github.event.inputs.username }}" "${{ env.Password }}"
    - name: IP for Connect to your SSH
      run: bash Ip.sh "${{ github.event.inputs.username }}" "${{ env.PINGGY_TOKEN }}"
    - name: Keep Alive
      run: ping 127.0.0.1 > null
